			headertextt.innerHTML = random_string()
			//yes this is how to java
			function random_string(){
				list_of_strings = ["Linking...","I'm moving past the feeling again","Living in the sprawl","spoon man","I hear your heart beat to the beat of the drums","Let's make the most of the night, like we're gonna die young","I made friends with a witch one day.","In four-hundred-thousand meters, turn right.","Where does this road go?","The sun is alone, yet shines the brightest.","Tonight, Gehrman joins the hunt.","Prepare yourself.","CAUTION!!!","woah its just like minecraft's flavor text!","I desperately wish to be included by the city's night!","I am fire!","Goldfish approved!","Today, a star of the city shall fall.","2.7182818284590452353602874713527","Explore beyond!","mods i spil my code hep hep help hep!!!","Sponsored by the Moon!","mmm soup","Making all kinds of stuff!","Fixing comedy one shitpost at a time!","NYOS Initialized! Welcome home!","What is a Yun?","All must serve the cycle!","These cats can, and will continue to hack robots like they've never hacked before!","Delete all that is unneeded!","Please select a save file!","You should try out Library of Runia!","Let's have a nice cup of tea!","Load/Save","Nothing escapes our gaze!","Witnessing reality!","I cant code help pls!","The solstice falls over Wintersoul!","Dango Dango Dango Daikazoku!","The cats that run this page like to make things!","Our reality was cruel, so we got rid of it!","Source 1.5 runs 48-bit","mmm soup","Source 1.5 runs 48-bit","Wrap yourself in cables and feel refreshed!","Treat every computer like a cat!","I love computers, so I turned myself into one!","Making nonsense since 2017!","What game will we play today!","What is a Metastruct?","The sound of thunder is thrilling indeed!","There are always rainbows after the storms!","Black cats deserve the most love!","Make sure to pet each and every cat!","Remember the good times, forget the new!","Forget reality, embrace the system!","Which computer will explode today?","To the Cat's eye, you are wonderful!","Learning one failure at a time!","Cat Computers love the cold!", "Chocolate is overrated!", "Snails are cute!"]

				chosensentence = Math.floor(Math.random() * list_of_strings.length)

				sentence = list_of_strings[chosensentence]

				return sentence
				}
				